GET http://localhost:3000/subscribers

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Arvids Answer from Server",
    "subscribedChannel": "Magic Channel"
}

###

GET http://localhost:3000/subscribers/5e302cf03294f92cf82ec8a1

###

DELETE http://localhost:3000/subscribers/5e302cd93294f92cf82ec8a0