
GET http://localhost:3000/posts

###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "author": "Arvid",
    "content": "Wieviel kosten roten Rosen?"
}

###

GET http://localhost:3000/subscribers/5e393e50d19d701d1087b35b

###

DELETE http://localhost:3000/posts/5e393e50d19d701d1087b35b

###

PATCH http://localhost:3000/posts/5e393e50d19d701d1087b35b
Content-Type: application/json

{
    "likedBy": ["Marco", "Rayk"]
}